version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=assef
      - POSTGRESQL_PASSWORD=q1w2e3
      - POSTGRESQL_DATABASE=apisolid